### ISSUE TITLE
Example spring-config.xml is missing

### ISSUE THREAD

**Issue by jspiewak** [awslabs/amazon-sqs-java-messaging-lib#1]
The code examples appear to reference the Spring configuration file, but the actual contents do not seem to appear anywhere.

It might also be nice if the code examples included in the [documentation](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/jmsclient.html#samples) were checked into the repo and were compilable.

**Comment by jspiewak** [comment]
And now it is there. Thanks!

**Comment by jackie-l** [comment]
Hi Joshua,

Thanks for the feedback! We have updated and fixed the documentation to include the referenced configuration file.

Thanks,
Jackie
