### ISSUE TITLE
Switch to AWS SQS SDK v2

### ISSUE THREAD

**Issue by oscerd** [awslabs/amazon-sqs-java-messaging-lib#103]
Is there any plan to switch to AWS SDK v2?

**Comment by sfragata** [comment]
There is a PR for that but I don't know when the aws guys are going to review it and merge it

https://github.com/awslabs/amazon-sqs-java-messaging-lib/pull/88

**Comment by oscerd** [comment]
Thanks for letting me know. It's been around for a long time.

**Comment by sfragata** [comment]
Yeah unfortunately :/

**Comment by tomhunte** [comment]
Looking at merging with the following PR https://github.com/awslabs/amazon-sqs-java-messaging-lib/pull/112. Reviewing changes now.

**Comment by ziyanli-amazon** [comment]
resolved issue: https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/2.0.0
