### ISSUE TITLE
SQSSessionCallbackScheduler race condition at close leave threads in waiting state for ever

### ISSUE THREAD

**Issue by wigtor** [awslabs/amazon-sqs-java-messaging-lib#105]
I have found a race condition when you create a SQSSession and inmediatly close it (For example when I only send a message I don't need any thread for listen messages).
In a production system after 2 days sending around 10000 messages, I have more than 100 threads in waiting state in line 102 of SQSSessionCallbackScheduler class (I see it using jstack command)
At construct a SQSSession, it construct an object SQSSessionCallbackScheduler and execute in a ExecutorService object tha make a thread. So, I have 2 threads: _main thread_ and _SQSSessionCallbackScheduler thread_, the execution order is:

- SQSSessionCallbackScheduler thread check "closed" variable and it is false (line 95 to line 97), context switch occurs
 before the _synchronized_ section in line 98.
- main thread call close() method, change "closed" variable to true
- main thread enter to _synchronized_ section
- main thread call notify() and it is never received by the QSSessionCallbackScheduler thread
- main thread exit of _synchronized_ section, context switch occurs
- SQSSessionCallbackScheduler thread enter to _synchronized_ section (line 98)
- SQSSessionCallbackScheduler thread check _callbackEntry == null_ (line 100)
- SQSSessionCallbackScheduler thread call wait() (line 102)

I propose check "closed" variable too into the _synchronized_ section (after line 98)
I attach an image of code explaining it.
![Screenshot_20211222_232601](https://user-images.githubusercontent.com/291719/147179610-ce137863-bd69-4258-8014-ad2fb6b3cf16.png)
![image](https://user-images.githubusercontent.com/291719/147181442-c8771872-76aa-44a1-b8fa-75f2e9ac1b9f.png)

**Comment by vghero** [comment]
That looks similar to what I saw during an AWS SQS outage, where DNS lookup of SQS endpoint were failing with `UnknownHostException`. The number of threads is rising very quickly until OOM errors occur - reaching 30k of those threads. Since the DNS lookup fails quickly, I guess it has the same issue like explained here. I will take a deeper look.

![image](https://user-images.githubusercontent.com/26437329/157844101-8207b64a-dbeb-413b-97ee-6c3cc73662bd.png)

**Comment by tomhunte** [comment]
Official update to fix this issue has been released today. Please let us know if this continues.

**Comment by ziyanli-amazon** [comment]
Please see the (latest release https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/1.0.9)
