### ISSUE TITLE
Version 1.0.9 not available as Maven dependency

### ISSUE THREAD

**Issue by mdeso** [awslabs/amazon-sqs-java-messaging-lib#110]
The latest version 1.0.9 is not available as Maven dependency, 20 days after release. But actually, the question is if this library is still supported. The recent release would suggest that but the AWS SDK depedency version is 1.11.106 which is of March 2017 and surely contains a lot of outdated transient dependencies. Someone mentioned a Jackson CVE in another issue.

**Comment by volkanto** [comment]
Hey hi, I want to use the latest version which contains the fix that we were waiting for long time. When the latest version will be pushed to maven repository? @eddy-aws

**Comment by volkanto** [comment]
hey hi @eddy-aws sorry for being pushy and bothering you, is there any estimated date to get this on maven repository? thx in advance.

**Comment by ziyanli-amazon** [comment]
I will take a look and try to publish the latest release

**Comment by volkanto** [comment]
@ziyanli-amazon is there any news about publish? looks like you already bump the version to `1.1.0`, so I assume you will publish both versions.

**Comment by tomhunte** [comment]
@volkanto - Sorry for the delay - we pushed to Maven, closing the issue, please let us know if you are experiencing any issues.

**Comment by ziyanli-amazon** [comment]
@volkanto Sorry for the delay. It is now live on Maven. Closing this issue.

**Comment by volkanto** [comment]
@tomhunte & @ziyanli-amazon thanks for your effort, really appreciated ✌️
