### ISSUE TITLE
Can we use an extended SQS client with the SQS connection factory?

### ISSUE THREAD

**Issue by navinvishy** [awslabs/amazon-sqs-java-messaging-lib#14]
It would be nice if we could use the extended SQS client that supports storing large messages in S3 with this JMS wrapper. I've submitted a [pull request](https://github.com/awslabs/amazon-sqs-java-messaging-lib/pull/13) for this. Could you please take a look and incorporate this in the library?

**Comment by kuba-aws** [comment]
Marked as feature request

**Comment by kuba-aws** [comment]
Feature has been added in version 1.0.3.
