### ISSUE TITLE
Switch from javax.jms.* to jakarta.jms.* to support Spring Boot 3

### ISSUE THREAD

**Issue by simonDeHero** [awslabs/amazon-sqs-java-messaging-lib#155]
Hi there,
i just tried to upgrade our app from Spring Boot 2.5.13 to 3.0.1. It turned out, that `spring-jms:6.0.3` expects some classes to be in `jakarta.jms` package, not in `javax.jms` anymore. E.g. `ConnectionFactory`, `JMSException`, `Message` or `Session`. This basically prevents me from upgrading to Spring Boot 3 now.

Those classes are provided transitively by `amazon-sqs-java-messaging-lib:1.1.0`, via the `geronimo-jms` dependency.

Do you have any plans to switch to `jakarta` package any time soon?

thx a lot!

**Comment by lena-pattern** [comment]
Hi, 
we have exact same issue.

We use the `amazon-sqs-java-messaging-lib` in almost of our microservices. We tried to upgrade to Spring Boot 3, but even the latest  versions of `amazon-sqs-java-messaging-lib` do not support Jakarta EE 9 APIs (that Spring Boot 3 uses in JMS implementation).  Meaning current `amazon-sqs-java-messaging-lib`  depends on `javax.jms.*` and not `jakarta.jms.*`, preventing us from upgrading to Spring Boot 3 (just like the OP).

Is there a roadmap for producing Spring Boot 3 compatible version? 

Thanks a lot!

**Comment by mauriciosolla** [comment]
I got a similar problem on my side :(

**Comment by mauriciosolla** [comment]
I got the same issue here. Any expectation for the switch to jakarta.jms?

**Comment by okohub** [comment]
Up!

+1

**Comment by volkanto** [comment]
maybe @ziyanli-amazon again can help us here?

**Comment by ziyanli-amazon** [comment]
Both v1 and v2 have been updated:
https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/1.1.3
https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/2.0.3

**Comment by armogur** [comment]
@ziyanli-amazon Hi, this isn't solved the mentioned issue, namely it is still in the javax.jms namespace, and not in the jakarta.jms.
I have a much more bigger patch, which updates not just to **jakarta** namespace but updates testing libraries, JDK to 17 (which is the minimum java version for SpringBoot 3).
If you think it worth to take a look at it let me know how can I share it.

**Comment by vghero** [comment]
> @ziyanli-amazon Hi, this isn't solved the mentioned issue, namely it is still in the javax.jms namespace, and not in the jakarta.jms. 

Exactly :). So what some projects do, is provide a version with jakarta deps and a 2nd one with still javax - for the projects that don't want or can't move yet. Question is if one wants to maintain two versions....

**Comment by AlexRosier** [comment]
> @ziyanli-amazon Hi, this isn't solved the mentioned issue, namely it is still in the javax.jms namespace, and not in the jakarta.jms. I have a much more bigger patch, which updates not just to **jakarta** namespace but updates testing libraries, JDK to 17 (which is the minimum java version for SpringBoot 3). If you think it worth to take a look at it let me know how can I share it.

This would be awesome I was working on the same thing myself since indeed the 2.0.3 version does not address the problem

**Comment by AlexRosier** [comment]
@armogur
Can you perhaps create a pull request with the code you have ?

**Comment by armogur** [comment]
> @armogur Can you perhaps create a pull request with the code you have ?

It looks like many PRs are in waiting state, some are several years old, I think the AWS lab not really cares about to improve this library, but if someone at amazon asks me I will be happy to publish it.

**Comment by Trebuac** [comment]
I'm interested by this one. It shouldn't have been closed as it doesn't fix the issue with old javax packages.
@armogur : is it possible to at least push your branch and create the PR ?

**Comment by okohub** [comment]
@ziyanli-amazon can you check that package transformation process please?

Unfortunately, problem is not solved with changing only dependency. Import statements must be changed as well.

**Comment by armogur** [comment]
@Trebuac, @AlexRosier :
Here is my PR: https://github.com/awslabs/amazon-sqs-java-messaging-lib/pull/177

**Comment by lena-pattern** [comment]
@ziyanli-amazon Hello, is there any possibility to check that PR#177 mentioned in the comment above and merge in the library to make it publicly available? This will help many of us a lot. Thanks!!

**Comment by ziyanli-amazon** [comment]
Yea, sorry for the late response. Will take a look

**Comment by ziyanli-amazon** [comment]
https://github.com/awslabs/amazon-sqs-java-messaging-lib/pull/182
