### ISSUE TITLE
control max messages received at once

### ISSUE THREAD

**Issue by esalter** [awslabs/amazon-sqs-java-messaging-lib#16]
In the normal SQS SDK, you can set the maximum number of messages to retrieve.  However I don't see an equivalent way to do that with this library.  I know you can set it to prefetch messages, but that seems to only affect the start of the session, then after that it looks like it receives 1 or 2 at a time.  Is there a way to do this that I'm not seeing?  It would be nice to do this since I know I'll be processing many thousands of messages so I may as well request a bunch at once to cut down on API requests.

My usecase involves setting up many worker threads, each with their own JMS queue and consumer reading from a single SQS queue, so I can process many messages in parallel.  I could be doing something wrong so if there's a way to do this I'm all ears.

**Comment by aws-bilgin** [comment]
Basically the prefetch size(maximum 10) you determine impacts the batch size on each receive call. For example, if your prefetch size is 10, and if consumer buffer does not have any messages and your SQS queue has available messages, then you can receive up to 10 messages in a single call based on the formula below:
prefetchBatchSize = Math.min(
                            (numberOfMessagesToPrefetch - messagesPrefetched), SQSMessagingClientConstants.MAX_BATCH);
But if your consumer buffer has some unconsumed messages (which means that your worker thread is not keeping up well in consuming messages) or your SQS queue has less than 10 messages available, each receive call can retrieve less than 10 messages.

See: https://github.com/awslabs/amazon-sqs-java-messaging-lib/blob/master/src/main/java/com/amazon/sqs/javamessaging/SQSMessageConsumerPrefetch.java

**Comment by esalter** [comment]
Hm...it's weird, because I was setting a prefetch value greater than 10 and I could see that inflight SQS messages matched the number I would expect (# of threads * prefetch size), however once they caught up or the messages timed out then all I saw inflight after that was (# of threads * 2).  Sounds like there may be a minor bug somewhere by letting it initially prefetch more.  I'll try it again with 10 for prefetch to see if that fixes it.  Thanks for your assistance!
