### ISSUE TITLE
constructor SQSConnectionFactory migrating from com.amazonaws » amazon-sqs-java-messaging-lib version 1.1.2 to 2.0.2

### ISSUE THREAD

**Issue by juparog** [awslabs/amazon-sqs-java-messaging-lib#161]
Hi, I am currently migrating from com.amazonaws » amazon-sqs-java-messaging-lib version 1.1.2 to 2.0.2.

the implementation of the method
```
public void start() {

AmazonSQS sqs = AmazonSQSClientBuilder.standard()
.withRegion(Regions.fromName(awsProperties.getRegion()))
.withCredentials(createAwsStaticCredentialsProvider())
.build up();

this.connectionFactory = new SQSConnectionFactory(new ProviderConfiguration(), sqs);
}
```

Fails for constructor: `this.connectionFactory = new SQSConnectionFactory(new ProviderConfiguration(), sqs);`

because SQSConnectionFactoryn does not accept AmazonSQS as a second argument.

I would like to know if you have any examples that you can give me for your new constructor.

Thank you and how attentive.

**Comment by ziyanli-amazon** [comment]
Hi, please check the imported class for some of the signature changes. i.e. `import software.amazon.awssdk.services.sqs.*;

To answer your specific question, you need to use `SqsClient` instead.
