### ISSUE TITLE
Inconsistent Maven deployment for com.amazonaws:amazon-sqs-java-messaging-lib 1.1.3

### ISSUE THREAD

**Issue by veita** [awslabs/amazon-sqs-java-messaging-lib#174]
Version 1.1.3 declares itself as 2.0.3 in the Maven deployed POM. This leads to failing builds.

https://repo1.maven.org/maven2/com/amazonaws/amazon-sqs-java-messaging-lib/1.1.3/amazon-sqs-java-messaging-lib-1.1.3.pom

Additionally, 1.1.3 is announced as 1.0.3 https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/1.1.3

**Comment by ziyanli-amazon** [comment]
Thanks. Apologize. Please use any prior semantic versions instead for java 1.x.
