### ISSUE TITLE
Library latest version is not compatible with spring version 6.0.x

### ISSUE THREAD

**Issue by minal107** [awslabs/amazon-sqs-java-messaging-lib#180]
Recently I have upgraded my project to spring version 6.0.x where javax libraries are replaced with jakarta.
I have been using this library to connect with amazon sqs and create connection between it but the connectionFactory is using javax imports which now must be replaced with jakarta package.

I found this as a blocker to upgrade my project to the latest version of spring.
Can you please look into this issue and let me know what is the best possible solution to resolve this?

**Comment by lbenedetto** [comment]
https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/155

**Comment by minal107** [comment]
@lbenedetto As this is a blocker for me to upgrade the spring version can you please let me know by when can I expect the resolution to the issue or if there is any workaround to fix this?

And in [#155](https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/155) someone has raised the PR to fix this import error, is there any possibility to check that PR and merge in the library to make it publicly available?

**Comment by lbenedetto** [comment]
I'm not affiliated with AWS, I'm just someone in the same situation as you. 

I don't have much hope of aws or some other libraries I depend on updating to jakarta any time soon. 
So instead, I'm working on a Gradle script to rewrite the bytecode of all my dependencies and force them to use Jakarta. I'll polish it up and make it available on GitHub when I'm done.

**Comment by lbenedetto** [comment]
@minal107 I've created a gist with my gradle code for bytecode remapping aws to use jakarta.
Personally, I prefer this over using a fork.
https://gist.github.com/lbenedetto/56da5ca72fdb61da96e954b5e2bd1d21

**Comment by manthesh21793** [comment]
facing the same problem

**Comment by ziyanli-amazon** [comment]
https://github.com/awslabs/amazon-sqs-java-messaging-lib/pull/182. Will merge it after internal review

**Comment by ziyanli-amazon** [comment]
For java 2.x - https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/2.1.0
