### ISSUE TITLE
Avoid pulling in Lombok as transitive dependency

### ISSUE THREAD

**Issue by vpavic** [awslabs/amazon-sqs-java-messaging-lib#189]
At present, this library pulls in Lombok as transitive dependency, which really shouldn't be the case as it is an annotation processor. See [Maven setup](https://projectlombok.org/setup/maven) on Lombok website.

Additionally, since Lombok doesn't appear to be heavily used (only in [two classes](https://github.com/search?q=repo%3Aawslabs%2Famazon-sqs-java-messaging-lib%20lombok&type=code)) in the project, I'd suggest removing it altogether in order to make the debugging easier. If you agree with this proposal, I'd gladly contribute a PR.

**Comment by ziyanli-amazon** [comment]
Sounds good @vpavic . Feel free to submit a PR and I will review it right away.

**Comment by vpavic** [comment]
Thanks for the feedback @ziyanli-amazon, I've opened #192.

**Comment by vpavic** [comment]
This is now basically a duplicate of #192 that has just been merged.
