### ISSUE TITLE
JMSCorrelationId is null on receiver side

### ISSUE THREAD

**Issue by christophercampbell** [awslabs/amazon-sqs-java-messaging-lib#19]
TextMessage's that have JMSCorrelationID set when received have null correlationId.

CorrelationID is useful for request/response patterns.

**Comment by eitansela** [comment]
I am also facing this issue.
As a workaround, I used StringProperty named "jMSCorrelationID" on the request message and then I can get it on the response message.

**Comment by kuba-aws** [comment]
Marked as feature request.
