### ISSUE TITLE
Support MDB

### ISSUE THREAD

**Issue by lowecg** [awslabs/amazon-sqs-java-messaging-lib#2]
I've attempted to configure this library with Wildfly 8.2.0 using its generic JMS support.  The generic JMS glue code makes some calls to the following methods which raise "method not supported" exceptions:

com.amazon.sqs.javamessaging.SQSSession#setMessageListener
com.amazon.sqs.javamessaging.SQSConnection#createConnectionConsumer(javax.jms.Queue, java.lang.String, javax.jms.ServerSessionPool, int)

Without support for MDB, this library does not support enough of the JMS feature set to consider using this library over our regular JMS brokers.

**Comment by aws-bilgin** [comment]
Thanks for the feedback! It really helps us for our planning of how best to meet customer needs. I would like to ask some follow-up questions:
   1-) What is your current JMS provider?
   2-) Does your set-up requires JNDI support as well?
   3-) Are you using message selectors or it is just a placeholder?

**Comment by lowecg** [comment]
Sorry for the delay in replying.

1) Our current provider is JBoss HornetQ
2) Yes it does, but this is managed by adding a JBoss module to Wildfly that contains an implementation of ObjectFactory to create connection factory and queue references. 
3) We're not using message selectors at this time (but it would be nice to know they are there for future use)

**Comment by mikesir87** [comment]
I, too, would be interested in this.  Here's my answers too (in case it matters):

1) Also using HornetQ, but have also used ActiveMQ.
2) We are creating the queues in the container, placing them at global JNDI references.  Then, in jboss-web.xml, creating local references that the app then binds to.  So, app doesn't know global names, but the aliased names.
3) No. Not using message selectors.

**Comment by beikov** [comment]
1) Using ActiveMQ
2) Yes
3) No, but future support for selectors would be very nice

Is MDB support something you are considering already or do you need more people requesting that feature?

**Comment by Mobe91** [comment]
I am also in need of proper MDB support:
1. Just started to build JMS into our system so there is no current provider
2. Yes
3. No, but would be nice
