### ISSUE TITLE
JMSTimestamp could be set to SentTimestamp ?

### ISSUE THREAD

**Issue by bat-cha** [awslabs/amazon-sqs-java-messaging-lib#20]
Hi awslabs !

I was wondering if it would make sense to set JMSTimestamp to SentTimestamp when converting from SQS message to JMS message

Thanks for your feedback if any

**Comment by kuba-aws** [comment]
Marked as feature request.

**Comment by vghero** [comment]
Is there any reason (besides the conflict) not to merge the related PR?

**Comment by vghero** [comment]
Anyone?

**Comment by devendra-dh** [comment]
@robin-aws is this repo only running in maintenance mode, thus this `feature request` is not being considered?

**Comment by vghero** [comment]
@bat-cha : still in the mood to fix the conflict in the PR to make @kuba-aws 's life easier :)?

**Comment by volkanto** [comment]
@eddy-aws it would be awesome if some of you guys can have a look and push forward this pull request. looking forward to your approvals 😃  🎉

**Comment by eddy-aws** [comment]
@volkanto can you rebase the PR?

**Comment by volkanto** [comment]
hey @eddy-aws I am not sure if the previous PR's owner is going to take care but to take quick action, I've prepared another one [here](https://github.com/awslabs/amazon-sqs-java-messaging-lib/pull/111). If the other one's owner takes action soon, please discard my pull request.
