### ISSUE TITLE
Spring boot 3.X - change to jakarta

### ISSUE THREAD

**Issue by maximus321** [awslabs/amazon-sqs-java-messaging-lib#219]
I see the dependency used in this lib is all using javax.
This lib is no longer present in recent Spring boot, is there plan to move to jakarta so we can use it in Spring Boot 3 and up?
Thanks!

**Comment by ziyanli-amazon** [comment]
Which version are you using?
please update if you are not on the latest version: https://github.com/awslabs/amazon-sqs-java-messaging-lib/blob/master/pom.xml#L60
