### ISSUE TITLE
Will this ever be packaged under software.amazon.awssdk for AWS SDK V2? 

### ISSUE THREAD

**Issue by chris-tuncap** [awslabs/amazon-sqs-java-messaging-lib#220]
I'm in the process of upgrading my gradle packages from V1 to V2.  I was wondering if there are plans for this to be packaged under `software.amazon.awssdk` instead of `com.amazonaws`?  I know this was already upgraded to support V2.

**Comment by ziyanli-amazon** [comment]
Hi, currently there's no plan to include the repo under another namespace.
