### ISSUE TITLE
Dependency on aws-java-sdk.version 1.9.6

### ISSUE THREAD

**Issue by sanjaypujare** [awslabs/amazon-sqs-java-messaging-lib#24]
I noticed that this library depends on aws-java-sdk-sqs version 1.9.6 which conflicts with aws-java core version 1.10.73 we would like to use. Can this dependency be upgraded to 1.10.73 since 1.9.6 seems quite old now? BTW, these 2 versions are incompatible as I found out the hard way

java.lang.NoSuchMethodError: com.amazonaws.AmazonWebServiceRequest.copyPrivateRequestParameters()Ljava/util/Map;

**Comment by jgangemi** [comment]
have you not tried just including the aws libraries you want directly in the pom and excluding the dependencies from this library? 

i am currently using this library w/ `1.10.56` just fine.

**Comment by sanjaypujare** [comment]
Thanks, I will try that. I wasn't aware of the POM dependency exclusion feature (I guess that's what you are referring to) and try 1.10.73.

**Comment by fgauthier** [comment]
An easy trap to fall into happens if you only add the following dependency to your pom:

		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk</artifactId>
			<version> {aws-sdk-version > 1.9.6} </version>
		</dependency>

Where: {aws-sdk-version > 1.9.6} is some version greater than 1.9.6

This will cause all aws jars to be included with the newer version except to the specific sqs jar - that one will still have version 1.9.6. The reason for this is due to the fact that the amazon-sqs-java-messaging-lib  pom includes an explicit version 1.9.6 dependency for the aws-java-sdk-sqs artifact. The resulting mismatched versions lead to the NoSuchMethodError above.

To avoid this make sure you have the following dependency in your pom:

		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-sqs</artifactId>
			<version> {aws-sdk-version > 1.9.6} </version>
		</dependency>

**Comment by sanjaypujare** [comment]
I tried jgangemi 's suggestion and it worked. Thx

**Comment by eitansela** [comment]
@sanjaypujare 
Have you modified the pom.xml of the amazon-sqs-java-messaging-lib jar and then you use it?
What should be the solution if I want to build it with gradle or maven? Then I will need my own repo to store this jar...

**Comment by sanjaypujare** [comment]
Use the exclusion feature described here
https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

This is for maven. Not sure about gradle.

**Comment by eitansela** [comment]
@sanjaypujare 
Thanks for the quick answer!
Can you attach this part in pom.xml you have done to make it work, with the exclusion?
Thanks again.

**Comment by sanjaypujare** [comment]
Here it is

<dependency>

      <groupId>com.amazonaws</groupId>

      <artifactId>aws-java-sdk-sqs</artifactId>

      <version>1.10.73</version>

      <scope>test</scope>

    </dependency>

    <dependency>

      <groupId>com.amazonaws</groupId>

      <artifactId>amazon-sqs-java-messaging-lib</artifactId>

      <version>1.0.0</version>

      <scope>test</scope>

      <exclusions>

        <exclusion>

          <groupId>com.amazonaws</groupId>

          <artifactId>aws-java-sdk-sqs</artifactId>

        </exclusion>

      </exclusions>

    </dependency>

**Comment by joshuadavis** [comment]
I've got a similar issue with `amazon-sqs-java-messaging-lib:1.0.0` and `aws-java-sdk-sqs:1.11.8`

When the message is being acknowledged the following exception is thrown:

`java.lang.NoSuchMethodError: com.amazonaws.services.sqs.AmazonSQS.deleteMessage(Lcom/amazonaws/services/sqs/model/DeleteMessageRequest;)V`

**Comment by jgangemi** [comment]
up to `1.10.77` works w/o issue. the `1.11.x` series seems to have broken compatibility (and aws needs to read up on semantic versioning).

hopefully we'll get a response on this soon.

**Comment by trex-amazon** [comment]
We are aware of this issue and are working on a fix. Stay tuned.

Trevor @ AWS

**Comment by jgangemi** [comment]
does that mean some of the other things ppl have asked for, etc might also get addressed given this library is gonna get some love?

**Comment by trex-amazon** [comment]
We are actively working on this JMS library and will continue to support it going forward.

**Comment by jgangemi** [comment]
awesome - i'd love to see #8 addressed since i want to use this library w/o the `jms` interface bits and catching exceptions that are never actually thrown is annoying, but that's a separate discussion.

**Comment by trex-amazon** [comment]
This issue is now fixed.

**Comment by jgangemi** [comment]
it's great that this is fixed but you guys need to read up on semantic versioning - i don't think this qualifies as a bug fix.

**Comment by sidath80** [comment]
Hi Team,

I am getting following error when try to conect to the AWS sqs with following libs,

		<aws.sdk.version>1.11.192</aws.sdk.version>

                <groupId>com.amazonaws</groupId>
			<artifactId>amazon-sqs-java-messaging-lib</artifactId>
			<version>1.0.0</version>

14:07:16,927 WARN  [org.springframework.jms.listener.DefaultMessageListenerContainer] Setup of JMS message listener invoker failed for destination 'testq' - trying to recover. Cause: com.amazonaws.services.sqs.AmazonSQS.deleteMessage(Lcom/amazonaws/services/sqs/model/DeleteMessageRequest;)V

thanks
