### ISSUE TITLE
Error Consuming Binary Messages from Amazon SQS in Java Application with JDK 1.8.0_402

### ISSUE THREAD

**Issue by bg-aws** [awslabs/amazon-sqs-java-messaging-lib#243]
It seems that the SQS JMS library does not seem to correctly identify the message attribute for the Binary type, leading to issues with reading the message data. 

JDK Version in Use:
openjdk version "1.8.0_402"
OpenJDK Runtime Environment (build 1.8.0_402-b06)
OpenJDK 64-Bit Server VM (build 25.402-b06, mixed mode)

The SQS Messaging client has the following String constants:
[+] https://github.com/awslabs/amazon-sqs-java-messaging-lib/blob/master/src/main/java/com/amazon/sqs/javamessaging/SQSMessagingClientConstants.java 

    public static final String STRING = "String";

    public static final String NUMBER = "Number";

    public static final String INT = "[Number.int](http://number.int/)";

    public static final String BOOLEAN = "Number.Boolean";

    public static final String BYTE = "Number.byte";

    public static final String DOUBLE = "Number.double";

    public static final String FLOAT = "Number.float";

    public static final String LONG = "Number.long";

In scenarios where the SQS message attribute type is set to Binary, the ‘type’ parameter variable is: value = “Binary”.
However, there is no constant for “Binary”, so when traversing the conditional branches of 

    private static Object getObjectValue(String value, String type) throws JMSException

the ‘type’ parameter will not enter any branch and subsequently throw an exception. 
[+] https://github.com/awslabs/amazon-sqs-java-messaging-lib/blob/master/src/main/java/com/amazon/sqs/javamessaging/message/SQSMessage.java

Similar issues have been reported on the GitHub over the years and there have been updates to address certain cases, specifically with custom attribute types, but no changes have seemingly been implemented to address the above. 
[+] https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/1.0.7
[+] https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/53 
[+] https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues?q=is%3Aissue+is%3Aopen+binary

**Comment by ziyanli-amazon** [comment]
https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/2.1.4
