### ISSUE TITLE
Why only one SQSSessionCallbackScheduler thread in a Session?

### ISSUE THREAD

**Issue by sunhelly** [awslabs/amazon-sqs-java-messaging-lib#28]
We can use multi-consumers in a Session, but only one SQSSessionCallbackScheduler.
Why not callback and ack in the prefetch thread?

**Comment by rendion** [comment]
Use more sessions.

**Comment by kuba-aws** [comment]
This is according to JMS specification. A particular Session object has to be single threaded and is not allowed to dispatch messages to MessageListener in parallel. You can use multiple Session objects if you need to process messages in parallel.

Quote from JMS specification:
> Since the session serializes execution of its consumer’s MessageListeners, they can safely share the resources of their session.
