### ISSUE TITLE
Can DelaySeconds be set on a Message using JMS?

### ISSUE THREAD

**Issue by mwaluk** [awslabs/amazon-sqs-java-messaging-lib#30]
I'd like to delay the delivery of certain messages, like the DelaySeconds message attribute (or message timers) but I wasn't sure how to do it with JMS.  A simple message attribute with that as the name?

**Comment by adressin** [comment]
+1

**Comment by SingleShot** [comment]
We would find this very useful for error handling / redelivery situations.

**Comment by mig281** [comment]
At this point, this functionality isn't possible. However, it _is_ on our roadmap.

**Comment by mecca831** [comment]
Any update on this functionality?

**Comment by blagerweij** [comment]
I have just created a Pull-Request for this:
https://github.com/awslabs/amazon-sqs-java-messaging-lib/pull/40

Please review and merge, we really need this feature in the main branch.
