### ISSUE TITLE
Add MessageGroupId and MessageDeduplicationId

### ISSUE THREAD

**Issue by AlexKovalevich** [awslabs/amazon-sqs-java-messaging-lib#31]
To enable publishing to SQS FIFI queues thise properties must be supported.

Class com.amazonaws.services.sqs.model.MessageSystemAttributeName has them defined but they are ignored by SQSMessageProducer and other classes.

If you add this code:
        final String groupId = message.getStringProperty(MessageSystemAttributeName.MessageGroupId.toString());
        final String deduplicationId = message.getStringProperty(MessageSystemAttributeName.MessageDeduplicationId.toString());
        if (groupId != null) {sendMessageRequest.setMessageGroupId(groupId);}
        if (deduplicationId != null) {sendMessageRequest.setMessageDeduplicationId(deduplicationId);}

TO THE:

SQSMessageProducer.sendInternal(Queue queue, Message message) 
right before 
String messageId = amazonSQSClient.sendMessage(sendMessageRequest).getMessageId();

And will send your JMS message with the following spring properties:
jmsMessage.setStringProperty(MessageSystemAttributeName.MessageDeduplicationId.toString(), myDeduplicationId);
jmsMessage.setStringProperty(MessageGroupId.MessageDeduplicationId.toString(), myMessageGroupId);

It will work.

**Comment by trex-amazon** [comment]
We are currently working to add support for FIFO queues to this library, so stay tuned.

**Comment by trex-amazon** [comment]
This is now supported. Let us know what you think.

**Comment by alicode95** [comment]
How do I set a `MessageGroupId` while sending message to a **FIFO queue** from a `JmsTemplate`?
