### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by ssdev17** [awslabs/amazon-sqs-java-messaging-lib#36]
Hi, Thank you for providing such an awesome JMS interface for SQS. Is there any plan for supporting Message Selectors while creating consumers from Session. If so then will greatly appreciate any tentative time lines for the availability for the same.

**Comment by kuba-aws** [comment]
Message Selectors cannot be implemented solely on client side. Support for Message Selectors will be included if SQS will support a similar feature server-side.

**Comment by kuba-aws** [comment]
Also, can you explain more about your use case for message selectors? They are typically an anti-pattern in the world of messaging -> the consumer should be able to consume any message from the queue, not seek particular messages.

**Comment by ziyanli-amazon** [comment]
closing stale issue
