### ISSUE TITLE
JMS Async messageListener Interface

### ISSUE THREAD

**Issue by Gitrdon3** [awslabs/amazon-sqs-java-messaging-lib#43]
Is there any way to make this implementation less aggressive (i.e. for Long Polling)?  We are using the async MessageListener interface and it becomes more aggressive over time.  After about 18-hours we're seeing 1+million empty messages API calls and growing.

**Comment by ziyanli-amazon** [comment]
Closing a stale issue. Feel free to re-open if the issue persists.
