### ISSUE TITLE
Access to more SQSTextMessage attributes

### ISSUE THREAD

**Issue by reecefenwick** [awslabs/amazon-sqs-java-messaging-lib#44]
Currently using 1.0.4 and I'm interested in getting the SentTimestamp property from SQSTextMessage, but unfortunately only ApproximateReceiveCount is mapped across as "JMSXDeliveryCount" at `SQSMessage.java:125`

Attributes that I can see coming from `com.amazonaws.services.sqs.model.Message`

![image](https://user-images.githubusercontent.com/7043425/31469698-1bfa063e-af26-11e7-9275-e586870bba4e.png)

Is this something that can be added?

**Comment by MrBuddyCasino** [comment]
At least those attributes could be mapped as message properties. There is currently no way to access them.

**Comment by ziyanli-amazon** [comment]
You can use the `getJMSTimestamp` in the `SQSMessageConsumerPrefetcher` to get the SentTimestamp.
