### ISSUE TITLE
SQSMessage.JMSMessagePropertyValue fails parsing message attributes on missing or unknown custom type

### ISSUE THREAD

**Issue by artamonovkirill** [awslabs/amazon-sqs-java-messaging-lib#50]
SQS message attribute custom type is optional free text.

[com.amazon.sqs.javamessaging.message.SQSMessage.JMSMessagePropertyValue.getObjectValue](https://github.com/awslabs/amazon-sqs-java-messaging-lib/blob/master/src/main/java/com/amazon/sqs/javamessaging/message/SQSMessage.java#L1193-L1216) only allows
- String without custom type: [STRING.equals(type)](https://github.com/awslabs/amazon-sqs-java-messaging-lib/blob/master/src/main/java/com/amazon/sqs/javamessaging/message/SQSMessage.java#L1194)
- Number with a hard-coded list of customer types: int, Boolean, byte, double, float, long, short.

So, the following message attribute types:
- String.foo
- Number
- Number.integer or Number.boolean
- Binary
- Binary.foo
will cause an [JMSException(type + " is not a supported JMS property type")](https://github.com/awslabs/amazon-sqs-java-messaging-lib/blob/master/src/main/java/com/amazon/sqs/javamessaging/message/SQSMessage.java#L1214)

[com.amazon.sqs.javamessaging.SQSMessageConsumerPrefetch.processReceivedMessages](https://github.com/awslabs/amazon-sqs-java-messaging-lib/blob/master/src/main/java/com/amazon/sqs/javamessaging/SQSMessageConsumerPrefetch.java#L283-L312) catches `JMSException` and does not acknowledge a message with one of the types above without other exception being raised or anything logged.

How I think types should be treated:
1. String / binary custom types might be disregarded.
2. Number missing / unknown type should default to something (long?)
3. At least an error should be logged if the message cannot be acknowledged due to `JMSException`.

**Comment by ziyanli-amazon** [comment]
https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/2.1.4
