### ISSUE TITLE
Unable to get IAM permissions from ECS task role

### ISSUE THREAD

**Issue by jeremyfryer** [awslabs/amazon-sqs-java-messaging-lib#51]
I tried to apply the IAM role to the ECS task role and the spring application was unable to pick up the IAM permissions. I had to apply the IAM role to the EC2 instances in the ECS cluster in order for the app to pick up the IAM permissions.

When a running a spring application in a docker container on ECS, I would like to place the IAM role on the ECS task definition instead of the EC2 instance(s).

**Comment by kuba-aws** [comment]
This looks like a question specific to ECS. Please ask your question on the ECS forum:
https://forums.aws.amazon.com/forum.jspa?forumID=187

Resolving.

**Comment by jeremyfryer** [comment]
The issue is with using this library on ECS. If I use the AWS Java SDK, that picks up the IAM permissions from the ECS Task role. When I use this library it is unable to pick up the IAM permissions.
