### ISSUE TITLE
Library throws exception when receiving SQS Messages that have documented data types.

### ISSUE THREAD

**Issue by benwynn** [awslabs/amazon-sqs-java-messaging-lib#60]
SQS Messages may have attributes on them with DataType values of 'String', 'Number', and 'Binary', as documented on https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html

Currently, the library throws a JMSException if it receives a Number or Binary and only handles String and a handful of 'Custom' types.  

A library that purports to join JMS and SQS should be able to, at the bare minimum of functionality,  consume perfectly normal SQS messages that meet the documentation for them.

**Comment by benwynn** [comment]
@kuba-aws Please see my PR that solves the above issue
 https://github.com/awslabs/amazon-sqs-java-messaging-lib/pull/59

**Comment by kdamevin** [comment]
Any update on this one? it's blocking me as well when using _amazon-sqs-java-extended-client-lib_ that relies on the "Number" data type

**Comment by benwynn** [comment]
So this isn't getting solved, and I've long moved on.  Closing issue.
