### ISSUE TITLE
message={ConsumerPrefetchThread-30} AmazonClientException: receiveMessage., com.amazonaws.SdkClientException: Unable to execute HTTP request: Address already in use: connect

### ISSUE THREAD

**Issue by tilakraj94** [awslabs/amazon-sqs-java-messaging-lib#69]
https://stackoverflow.com/questions/53727538/aws-sdk-exception-port-already-in-use

The issue has been completely described on the link. 

I think this case needs to be handled. All i see print stack traces in the console and ultimately halting my paralled execution. It goes for a while and then the execution resumes.

**Comment by ziyanli-amazon** [comment]
Closing a stale issue. Feel free to re-open if the issue persists.
