### ISSUE TITLE
Does amazon-sqs-java-messaging-lib support "once and only once" delivery?

### ISSUE THREAD

**Issue by lucasweb78** [awslabs/amazon-sqs-java-messaging-lib#7]
As per the SQS FAQs http://aws.amazon.com/sqs/faqs/

```
Q: How many times will I receive each message?

Amazon SQS is engineered to provide “at least once” delivery of all messages in its queues. 
Although most of the time each message will be delivered to your application exactly once, 
you should design your system so that processing a message more than once does 
not create any errors or inconsistencies. 
```

Does the amazon-sqs-java-messaging-lib do anything to address this or is it still the responsibility of the application to deal with this?

**Comment by aws-bilgin** [comment]
It is still responsibility of the application to deal with “at least once” delivery. amazon-sqs-java-messaging-lib supports the JMS acknowledge modes such as "auto" to eliminate the possibility of forgotten acknowledges for the messages that were processed.

**Comment by lucasweb78** [comment]
Thanks for the clarification. Are there any plans to in the future to provide "at most once"?

**Comment by aws-bilgin** [comment]
Just for clarification purposes, so would you be OK with losing messages and you are interested in non-persistent delivery mode?

**Comment by lucasweb78** [comment]
I'm actually interested in "once and only once" delivery not "at most once" sorry for the confusion.

In JMS terms I'm looking for PERSISTENT delivery where

```
A message is guaranteed to be delivered once and only once by a JMS provider if 
the delivery mode of the message is PERSISTENT and if the destination has a sufficient message retention policy.
```

**Comment by trex-amazon** [comment]
Once and only once delivery is now supported with SQS FIFO queues.
