### ISSUE TITLE
Endless loop on ExpiredToken in SQSMessageConsumerPrefetch

### ISSUE THREAD

**Issue by dastraka** [awslabs/amazon-sqs-java-messaging-lib#85]
Client is expecting to receive JMSException as a trigger to refresh token but it never comes. Need a maximum retry or something to trigger exception to client. Using amazon-sqs-java-messaging-lib 1.0.8.

Service Log:
=========
02/13/2020 08:14:29,404  WARN [ConsumerPrefetchThread-1] SQSMessageConsumerPrefetch - Encountered exception during receive in ConsumerPrefetch thread
javax.jms.JMSException: AmazonServiceException: receiveMessage. RequestId: aac7fbd9-e23a-5e7e-9d9d-ad66be3f2d80
HTTPStatusCode: 403 AmazonErrorCode: ExpiredToken
	at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.handleException(AmazonSQSMessagingClientWrapper.java:432)
	at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.receiveMessage(AmazonSQSMessagingClientWrapper.java:353)
	at com.amazon.sqs.javamessaging.SQSMessageConsumerPrefetch.getMessages(SQSMessageConsumerPrefetch.java:259)
	at com.amazon.sqs.javamessaging.SQSMessageConsumerPrefetch.getMessagesWithBackoff(SQSMessageConsumerPrefetch.java:303)
	at com.amazon.sqs.javamessaging.SQSMessageConsumerPrefetch.run(SQSMessageConsumerPrefetch.java:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Offending code:
============
    protected List<Message> getMessagesWithBackoff(int batchSize) throws InterruptedException {
        try {
            List<Message> result = getMessages(batchSize, WAIT_TIME_SECONDS);
            retriesAttempted = 0;
            return result;
        } catch (JMSException e) {
            LOG.warn("Encountered exception during receive in ConsumerPrefetch thread", e);
            try {
                sleep(backoffStrategy.delayBeforeNextRetry(retriesAttempted++));
                return Collections.emptyList();
            } catch (InterruptedException ex) {
                LOG.warn("Interrupted while retrying on receive", ex);
                throw ex;
            }
        }
    }

**Comment by kmbotts** [comment]
We had a similar issue with our session creds. We would wait until we received a specific Exception to essentially re-authenticate and get new session token and retry the call. It was a reactive approach that just didn't work for us at scale. So I ran into the **RequestHandler2** abstract class and implemented my own AWS refresher handler.

You'll need to have your Credentials implementation implement the **AWSRefreshableSessionCredentials** interface from AWS SDK and the **refreshCredentials()** method. That will contain your logic for determining if your creds have expired. I believe most Session Credentials have an expiration date in them. so we compare that to the current time, and if we're over, then make a call to the re-authentication logic to get fresh token.

The **beforeRequest** method is all you need to implement, it will check your token for expiration for every request.

```java
public class AWSRefreshRequestHandler extends RequestHandler2 {
    public AWSRefreshRequestHandler() {
    }

    @Override
    public void beforeRequest(Request<?> request) {
        AWSCredentials credentials = request.getHandlerContext(HandlerContextKey.AWS_CREDENTIALS);
        if (credentials instanceof AWSRefreshableSessionCredentials) {
            AWSRefreshableSessionCredentials refreshableSessionCredentials = (AWSRefreshableSessionCredentials) credentials;
            refreshableSessionCredentials.refreshCredentials();
        }
    }
}
```

Initialize your SQS clientBuilder and pass into SQSConnectionFactory
```java
    public void canCreateFactoryWithCustomBuilder() throws JMSException {
        AmazonSQSClientBuilder clientBuilder = AmazonSQSClientBuilder.standard()
                // AWSCredentialsProvider with AWSRefreshableSessionCredentials implementation
                //.withCredentials(new AWSCredentialsProvider)
                .withRequestHandlers(new AWSRefreshRequestHandler())
                .withRegion(Regions.US_EAST_1);
        SQSConnectionFactory factory = new SQSConnectionFactory(new ProviderConfiguration(), clientBuilder);
        SQSConnection connection = factory.createConnection();
        connection.close();
    }
```
Note: Our underling AWSCredentialsProvider is also shared to more than just SQS. Things like S3 and Kinesis. They all used the same provider and ultimately the same token, so the first one to detect an expiration would refresh. To prevent a race condition on re-auth, we had to put a locking mechanism in place to ensure that only one client would do the re-auth and the others coming in later would just pick up the new token as the expiration would be refreshed. Something to think about in your implementation.

Hope that helps.

**Comment by dastraka** [comment]
Thanks for the reply! The RequestHandler2 is what I needed although, I still get the exception even after getting a new token. I am not doing a connection.close() on my SQSConnection, could that be the issue?
