### ISSUE TITLE
No way to turn off or configure logging directly for sending sqs messages

### ISSUE THREAD

**Issue by nissimlavy** [awslabs/amazon-sqs-java-messaging-lib#9]
From looking at the code, it doesn't seem like there is any way to configure sqs and disable or limit logging when sending to sqs. So if I'm sending thousands of messages per few seconds, that generates a lot of logs and hurts performance

**Comment by kuba-aws** [comment]
You can tweak the logging level in log4j directly.
I'm also marking this as feature request, so that all log.X statements are wrapped in check if the logging is enabled on that level (to avoid creating log message strings).

**Comment by abhyudayareddy** [comment]
Is this enhancement released?
